# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 182c97e6a3a5875359b6e5d97cb968399068da44efeca1467991c6e5b382eac5cc0ba49db2564807d153a536b94fb4e1dd5552b2bcc78ad822897fa940cd448a

test:
  secret_key_base: 610e8e096d253e81189ef76356e9bc9b1ff2058efb76148b35a0c4acf9bf70583e1a57b5e0a9aa4f235efddc9ada83c9551584c26eedf2dbd45ee02afbb59520

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
